{% set name = "garnett" %}
{% set version = "0.7.1" %}
{% set sha256 = "cdf53f0ed66c3b70242069e0bc7e715537672d6ae228188ec5fe954ebf6f9e34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/garnett/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - deprecation >=2
    - numpy >=1.14
    - python >=3.5
    - rowan >=1.2
    - tqdm >=4.35

test:
  imports:
    - garnett

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'This is a collection of samples, parsers and writers for formats used in the Glotzer Group at the University of Michigan, Ann Arbor.'
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - lyrivera
    - klywang
    - bdice
    - joaander
