travis:
  secure:
    BINSTAR_TOKEN: dlGxFhGg+QLwgH89mODfBR47N5KcmpyFu3/PS6dBF6A/9NM5K/AAS1ticks+2gkgLtYiJEP2fY1gs0Wgx887E4+sgTQjQxtmXhYyxsfISJT8oN194nGWwLsg+ab5cmXl47bNS2xzXDvUQWtnQ8hHlRHUJkZ7nGBTJUqz9W+CDpNL2kW/vPq2O2vmD9eH75tKrB2rBl8/uM58epTsnCUHvDQKBFYWIykMAI71GWx96CV1Wt3VxQnhcj1gALGxwiI+7kHzGRAinsP4TMV3HUWR+KYqk+Ck/jXlKJ7HZ8BkDPfWjkJ8FYKcjTBe2bfWR3GWXpepKswa7H2GKENSwQ+RC8dgMFUqarj6Ket7e40xih6i4AnQpQIrIACiqcoXOcQvs7WRTyo8s/ikhdx7RFKsoHAgNDCQPit1UhHESKA9mi8SM8TaFrQ9nwEoArEjnjyqHuYBHrJnoG5LjqjmlRUf3TOy+8TNCxRcL2tryFzwk6e5qxq7lq3S7k23h02ymJNEKuAl4KelrZivkKA1lbvvKR0Yauid8WepNPxTLMqXido8YQ9URv6etbQNgbo7qj49J9sthHdBqD2O0H5ywCERWOVlTO5J8jvAk7tPzXtguu95l2Bi1QoXJGpWNy19lF2Vet+TjUqI18QiW3meqxkA1NnDyFoo0ZvOKLhB2FTStS8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
